P0_RM1:
  name: TMM
  offset: 40    # mm
  pitch: 0.25   #mm
  nstrips: 360    #mm
  nlayers: 2
  reconstruct_x: True
  reconstruct_y: True
  min_strips_in_cluster: 5 #if less than two cannot fit
  max_strips_in_cluster: 9999    # not a useful cut
  min_cluster_charge: 100   # ADC counts
  min_strip_charge: 60    # ADC counts
  max_n_consecutive_holes_in_cluster : 10 #1
  do_time_fit : False
  masked_strips:
    - -1
    - -2

P2_M01:
  name: ExMe
  offset: 224   # mm
  gap: 50.128   # mm
  pitch: 0.4   #mm
  nstrips: 1024
  nlayers: 1
  reconstruct_x: True
  reconstruct_y: False
  min_strips_in_cluster: 8 #if less than two cannot fit    
  max_strips_in_cluster: 9999    # not a useful cut
  min_cluster_charge: 100   # ADC counts
  min_strip_charge: 60    # ADC counts
  max_n_consecutive_holes_in_cluster : 1
  do_time_fit : False
  EFF_WINDOW: 50
  masked_strips: 
    - -1
    - -2

general:
  verbose : True
  NMAXEVENTS : 1 # fraction of events to process
  show_tracks : False
  do_time_fit: True
  plot_apv_signals: False

paths:
  raw_dir: data/raw/    # directory to apv raw files
  plots_dir:  results/plots/    # directory to save plots
  histo_dir: results/histos/   # directory to save histograms

units:
  length: mm
  time: ns
  speed: mm/ns
  charge : ADC Counts

gas:
  name: ArCF4Iso
  composition: (88:10:2)
  drift_speed: 0.105    # mm/ns

visualization:
  ExMeColor = 

apv:
  nbins: 27
  bin_width: 25   #ns
  charge_error: 1   #to be checked

mapping:
  x_readout_id: 89 # id of mmReadout used for x coordinate
  y_readout_id: 88 # id of mmReadout used for x coordinate





  